# Generated by Django 4.2.10 on 2024-02-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
