# Generated by Django 4.2.10 on 2024-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_company_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='assets',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='grossprofit',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='liabilities',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='netprofit',
            field=models.BigIntegerField(null=True),
        ),
    ]
