# Generated by Django 4.2.10 on 2024-03-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
